### ISSUE TITLE
This version is currently out of date and is recommended you download the updated one. https://github.com/itsunderscores/Instagram-Auto-Claimer-Swapper 3.1

### ISSUE THREAD

**Issue by l29** [itsunderscores/Instagram-Auto-Claimer-Swapper#1]
Just installed the requirements and run python main.py

Error Message:
This version is currently out of date and is recommended you download the updated one. https://github.com/itsunderscores/Instagram-Auto-Claimer-Swapper
3.1

**Comment by itsunderscores** [comment]
Fixed. Thanks.
